apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - namespace.yaml
  - postgres/deployment.yaml
  - redis/deployment.yaml
  - api/serviceaccount.yaml
  - api/configmap.yaml
  - api/secret.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml
  - api/pdb.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of:    ecommerce-platform
