apiVersion: v1
kind: Service
metadata:
  name: ecommerce-api
  labels:
    app: ecommerce-api
    app.kubernetes.io/name: ecommerce-api
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: ecommerce-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
